-- Migration 040: Fix NULL project_id breaking ON CONFLICT upserts
--
-- PostgreSQL treats NULL as distinct in UNIQUE constraints. The inline
-- UNIQUE constraints on ai_usage_daily and ai_usage_monthly allowed
-- unbounded row growth when project_id was NULL because ON CONFLICT
-- would never match. This migration replaces them with functional
-- unique indexes that use COALESCE to treat NULL as a sentinel UUID.

BEGIN;

-- ─── ai_usage_daily: drop old constraint, create functional index ───
-- The inline UNIQUE constraint name is auto-generated by Postgres as
-- <table>_<columns>_key. Drop it if it exists, then create the new index.
DO $$
BEGIN
  -- Try dropping the auto-named constraint
  ALTER TABLE ai_usage_daily
    DROP CONSTRAINT IF EXISTS ai_usage_daily_date_user_id_workspace_id_project_id_provid_key;
EXCEPTION WHEN undefined_object THEN
  -- Constraint doesn't exist (maybe already dropped or named differently)
  NULL;
END;
$$;

-- Also try the shorter truncated name Postgres might have used
DO $$
BEGIN
  ALTER TABLE ai_usage_daily
    DROP CONSTRAINT IF EXISTS ai_usage_daily_date_user_id_workspace_id_project_id_provi_key;
EXCEPTION WHEN undefined_object THEN
  NULL;
END;
$$;

-- Drop old index if it exists (in case someone already partially applied a fix)
DROP INDEX IF EXISTS idx_daily_unique;

CREATE UNIQUE INDEX IF NOT EXISTS idx_daily_unique
  ON ai_usage_daily(date, user_id, workspace_id, COALESCE(project_id, '00000000-0000-0000-0000-000000000000'::uuid), provider, model);

-- ─── ai_usage_monthly: drop old constraint, create functional index ─
DO $$
BEGIN
  ALTER TABLE ai_usage_monthly
    DROP CONSTRAINT IF EXISTS ai_usage_monthly_month_user_id_workspace_id_project_id_pro_key;
EXCEPTION WHEN undefined_object THEN
  NULL;
END;
$$;

DO $$
BEGIN
  ALTER TABLE ai_usage_monthly
    DROP CONSTRAINT IF EXISTS ai_usage_monthly_month_user_id_workspace_id_project_id_pr_key;
EXCEPTION WHEN undefined_object THEN
  NULL;
END;
$$;

DROP INDEX IF EXISTS idx_monthly_unique;

CREATE UNIQUE INDEX IF NOT EXISTS idx_monthly_unique
  ON ai_usage_monthly(month, user_id, workspace_id, COALESCE(project_id, '00000000-0000-0000-0000-000000000000'::uuid), provider, model);

-- ─── Deduplicate existing rows ──────────────────────────────────────
-- If unbounded row growth already occurred, collapse duplicate NULL
-- project_id rows by keeping only the one with the highest request_count
-- and summing the rest into it.
WITH daily_dupes AS (
  SELECT id,
    ROW_NUMBER() OVER (
      PARTITION BY date, user_id, workspace_id,
        COALESCE(project_id, '00000000-0000-0000-0000-000000000000'::uuid),
        provider, model
      ORDER BY request_count DESC, id
    ) AS rn
  FROM ai_usage_daily
)
DELETE FROM ai_usage_daily WHERE id IN (
  SELECT id FROM daily_dupes WHERE rn > 1
);

WITH monthly_dupes AS (
  SELECT id,
    ROW_NUMBER() OVER (
      PARTITION BY month, user_id, workspace_id,
        COALESCE(project_id, '00000000-0000-0000-0000-000000000000'::uuid),
        provider, model
      ORDER BY request_count DESC, id
    ) AS rn
  FROM ai_usage_monthly
)
DELETE FROM ai_usage_monthly WHERE id IN (
  SELECT id FROM monthly_dupes WHERE rn > 1
);

COMMIT;
