import type { ProviderPreset } from "./provider-types";

// ─── Capability Defaults ──────────────────────────────────

const CLOUD_CAPS_FULL = {
  streaming: true,
  toolCalling: true,
  vision: true,
  imageGeneration: false,
  video: false,
  audio: false,
  mcp: false,
} as const;

const CLOUD_CAPS_NO_VISION = {
  ...CLOUD_CAPS_FULL,
  vision: false,
} as const;

const LOCAL_CAPS_FULL = {
  streaming: true,
  toolCalling: true,
  vision: true,
  imageGeneration: false,
  video: false,
  audio: false,
  mcp: false,
} as const;

const LOCAL_CAPS_MINIMAL = {
  streaming: true,
  toolCalling: false,
  vision: false,
  imageGeneration: false,
  video: false,
  audio: false,
  mcp: false,
} as const;


export const CLOUD_MAJOR_PROVIDERS = [
  // ═══════════════════════════════════════════════════════════
  // Tier 1 — Major Cloud (6)
  // ═══════════════════════════════════════════════════════════
  {
    id: "openai",
    name: "OpenAI",
    category: "cloud",
    subcategory: "major",
    sdkType: "openai",
    defaultBaseUrl: "https://api.openai.com/v1",
    baseUrlEditable: true,
    authMethod: "bearer",
    apiKeyPrefix: "sk-",
    apiKeyPlaceholder: "sk-...",
    apiKeyHelpUrl: "https://platform.openai.com/api-keys",
    supportsModelDiscovery: true,
    defaultModels: [
      { id: "gpt-5.5", name: "GPT-5.5", contextWindow: 1_000_000, supportsTools: true, supportsVision: true, tier: "powerful" },
      { id: "gpt-5.5-pro", name: "GPT-5.5 Pro", contextWindow: 1_000_000, supportsTools: true, supportsVision: true, tier: "powerful" },
      { id: "gpt-5.4", name: "GPT-5.4", contextWindow: 1_000_000, supportsTools: true, supportsVision: true, tier: "powerful" },
      { id: "gpt-5.4-mini", name: "GPT-5.4 Mini", contextWindow: 400_000, supportsTools: true, supportsVision: true, tier: "balanced" },
      { id: "gpt-5.4-nano", name: "GPT-5.4 Nano", contextWindow: 400_000, supportsTools: true, supportsVision: true, tier: "fast" },
      { id: "gpt-4.1", name: "GPT-4.1", contextWindow: 1_047_576, supportsTools: true, supportsVision: true, tier: "balanced" },
      { id: "gpt-4.1-mini", name: "GPT-4.1 Mini", contextWindow: 1_047_576, supportsTools: true, supportsVision: true, tier: "fast" },
      { id: "gpt-4o", name: "GPT-4o", contextWindow: 128_000, supportsTools: true, supportsVision: true, tier: "balanced" },
      { id: "o3", name: "o3", contextWindow: 200_000, supportsTools: true, supportsVision: true, tier: "powerful" },
      { id: "o4", name: "o4", contextWindow: 200_000, supportsTools: true, supportsVision: true, tier: "powerful" },
      { id: "o4-mini", name: "o4-mini", contextWindow: 200_000, supportsTools: true, supportsVision: false, tier: "fast" },
    ],
    icon: "openai",
    description: "GPT-5.5, GPT-5.4, GPT-4.1, o3, o4, and more — the full OpenAI lineup",
    capabilities: CLOUD_CAPS_FULL,
    tags: ["popular", "gpt", "reasoning"],
  },
  {
    id: "anthropic",
    name: "Anthropic",
    category: "cloud",
    subcategory: "major",
    sdkType: "anthropic",
    defaultBaseUrl: "https://api.anthropic.com",
    baseUrlEditable: true,
    authMethod: "api-key",
    apiKeyPrefix: "sk-ant-",
    apiKeyPlaceholder: "sk-ant-...",
    apiKeyHelpUrl: "https://console.anthropic.com/settings/keys",
    supportsModelDiscovery: true,
    defaultModels: [
      { id: "claude-opus-4-7", name: "Claude Opus 4.7", contextWindow: 200_000, supportsTools: true, supportsVision: true, tier: "powerful" },
      { id: "claude-opus-4-6", name: "Claude Opus 4.6", contextWindow: 200_000, supportsTools: true, supportsVision: true, tier: "powerful" },
      { id: "claude-sonnet-4-6", name: "Claude Sonnet 4.6", contextWindow: 200_000, supportsTools: true, supportsVision: true, tier: "balanced" },
      { id: "claude-haiku-4-5", name: "Claude Haiku 4.5", contextWindow: 200_000, supportsTools: true, supportsVision: true, tier: "fast" },
    ],
    icon: "anthropic",
    description: "Claude Opus 4.7, Sonnet 4.6, and Haiku 4.5 from Anthropic",
    capabilities: CLOUD_CAPS_FULL,
    tags: ["popular", "claude", "reasoning"],
  },
  {
    id: "google-ai-studio",
    name: "Google AI Studio (Gemini)",
    category: "cloud",
    subcategory: "major",
    sdkType: "openai",
    defaultBaseUrl: "https://generativelanguage.googleapis.com/v1beta/openai/",
    baseUrlEditable: true,
    authMethod: "bearer",
    apiKeyPrefix: "AIza",
    apiKeyPlaceholder: "AIza...",
    apiKeyHelpUrl: "https://aistudio.google.com/apikey",
    supportsModelDiscovery: true,
    defaultModels: [
      { id: "gemini-3.1-pro-preview", name: "Gemini 3.1 Pro", contextWindow: 1_000_000, supportsTools: true, supportsVision: true, tier: "powerful" },
      { id: "gemini-3.5-flash", name: "Gemini 3.5 Flash", contextWindow: 1_000_000, supportsTools: true, supportsVision: true, tier: "fast" },
      { id: "gemini-2.5-pro", name: "Gemini 2.5 Pro", contextWindow: 1_000_000, supportsTools: true, supportsVision: true, tier: "powerful" },
      { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash", contextWindow: 1_000_000, supportsTools: true, supportsVision: true, tier: "fast" },
      { id: "gemini-2.5-flash-lite", name: "Gemini 2.5 Flash-Lite", contextWindow: 1_000_000, supportsTools: true, supportsVision: true, tier: "fast" },
    ],
    icon: "google",
    description: "Gemini 3.1 Pro, 3.5 Flash, 2.5 Pro and Flash via Google AI Studio",
    capabilities: CLOUD_CAPS_FULL,
    tags: ["popular", "gemini", "multimodal"],
  },
  {
    id: "azure-openai",
    name: "Azure OpenAI",
    category: "cloud",
    subcategory: "major",
    sdkType: "azure",
    defaultBaseUrl: "https://{resource}.openai.azure.com/openai/v1/",
    baseUrlEditable: true,
    baseUrlTemplate: true,
    authMethod: "azure-key",
    apiKeyPlaceholder: "Azure API key",
    apiKeyHelpUrl: "https://portal.azure.com/#view/Microsoft_Azure_ProjectOxford/CognitiveServicesHub",
    supportsModelDiscovery: true,
    defaultModels: [
      { id: "gpt-5.5", name: "GPT-5.5", contextWindow: 1_000_000, supportsTools: true, supportsVision: true, tier: "powerful" },
      { id: "gpt-5.4", name: "GPT-5.4", contextWindow: 1_000_000, supportsTools: true, supportsVision: true, tier: "powerful" },
      { id: "gpt-4.1", name: "GPT-4.1", contextWindow: 1_047_576, supportsTools: true, supportsVision: true, tier: "balanced" },
      { id: "gpt-4o", name: "GPT-4o", contextWindow: 128_000, supportsTools: true, supportsVision: true, tier: "balanced" },
    ],
    icon: "azure",
    description: "OpenAI models hosted on Microsoft Azure (GPT-5.5, 5.4, 4.1, 4o)",
    capabilities: CLOUD_CAPS_FULL,
    tags: ["enterprise", "azure", "gpt"],
  },
  {
    id: "aws-bedrock",
    name: "AWS Bedrock",
    category: "cloud",
    subcategory: "major",
    sdkType: "openai",
    defaultBaseUrl: "https://bedrock-runtime.{region}.amazonaws.com/openai/v1",
    baseUrlEditable: true,
    baseUrlTemplate: true,
    authMethod: "aws-sig",
    apiKeyPlaceholder: "AWS Access Key ID",
    apiKeyHelpUrl: "https://docs.aws.amazon.com/bedrock/latest/userguide/getting-started.html",
    supportsModelDiscovery: true,
    defaultModels: [
      { id: "claude-sonnet-4", name: "Claude Sonnet 4", contextWindow: 200_000, supportsTools: true, supportsVision: true, tier: "balanced" },
    ],
    icon: "aws",
    description: "Foundation models via AWS Bedrock (Claude, Llama, etc.)",
    capabilities: CLOUD_CAPS_FULL,
    tags: ["enterprise", "aws", "claude"],
  },
  {
    id: "google-vertex",
    name: "Google Vertex AI",
    category: "cloud",
    subcategory: "major",
    sdkType: "openai",
    defaultBaseUrl: "https://{region}-aiplatform.googleapis.com/v1/projects/{project}/locations/{region}/endpoints/openapi",
    baseUrlEditable: true,
    baseUrlTemplate: true,
    authMethod: "gcp-oauth",
    apiKeyPlaceholder: "GCP OAuth token",
    apiKeyHelpUrl: "https://cloud.google.com/vertex-ai/docs/start/cloud-environment",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "google-cloud",
    description: "Google Vertex AI with Gemini, Claude, and more",
    capabilities: CLOUD_CAPS_FULL,
    tags: ["enterprise", "gcp", "gemini"],
  },

  // ═══════════════════════════════════════════════════════════
  // Tier 2 — Aggregators (4)
  // ═══════════════════════════════════════════════════════════
  {
    id: "openrouter",
    name: "OpenRouter",
    category: "cloud",
    subcategory: "aggregator",
    sdkType: "openai",
    defaultBaseUrl: "https://openrouter.ai/api/v1",
    baseUrlEditable: false,
    authMethod: "bearer",
    apiKeyPrefix: "sk-or-v1-",
    apiKeyPlaceholder: "sk-or-v1-...",
    apiKeyHelpUrl: "https://openrouter.ai/keys",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "openrouter",
    description: "Access 200+ models from all providers through one API",
    capabilities: CLOUD_CAPS_FULL,
    freeTier: "28+ free models",
    tags: ["free", "aggregator", "popular"],
  },
  {
    id: "together-ai",
    name: "Together AI",
    category: "cloud",
    subcategory: "aggregator",
    sdkType: "openai",
    defaultBaseUrl: "https://api.together.xyz/v1",
    baseUrlEditable: false,
    authMethod: "bearer",
    apiKeyPlaceholder: "Together AI API key",
    apiKeyHelpUrl: "https://api.together.ai/settings/api-keys",
    supportsModelDiscovery: true,
    defaultModels: [
      { id: "meta-llama/Llama-3.3-70B-Instruct-Turbo", name: "Llama 3.3 70B", contextWindow: 128_000, supportsTools: true, supportsVision: false, tier: "balanced" },
      { id: "mistralai/Mistral-7B-Instruct-v0.3", name: "Mistral 7B", contextWindow: 32_000, supportsTools: false, supportsVision: false, tier: "fast" },
    ],
    icon: "together",
    description: "Open-source models with fast inference",
    capabilities: CLOUD_CAPS_FULL,
    freeTier: "$25 free credits",
    tags: ["free", "aggregator", "open-source", "popular"],
  },
  {
    id: "fireworks-ai",
    name: "Fireworks AI",
    category: "cloud",
    subcategory: "aggregator",
    sdkType: "openai",
    defaultBaseUrl: "https://api.fireworks.ai/inference/v1",
    baseUrlEditable: false,
    authMethod: "bearer",
    apiKeyPrefix: "fw_",
    apiKeyPlaceholder: "fw_...",
    apiKeyHelpUrl: "https://fireworks.ai/account/api-keys",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "fireworks",
    description: "Blazing-fast inference for open-source models",
    capabilities: CLOUD_CAPS_FULL,
    freeTier: "$1 free credits",
    tags: ["free", "aggregator", "fast", "popular"],
  },
  {
    id: "unify-ai",
    name: "Unify AI",
    category: "cloud",
    subcategory: "aggregator",
    sdkType: "openai",
    defaultBaseUrl: "https://api.unify.ai/v0",
    baseUrlEditable: false,
    authMethod: "bearer",
    apiKeyPlaceholder: "Unify AI API key",
    apiKeyHelpUrl: "https://console.unify.ai/",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "unify",
    description: "Smart routing across LLM providers for optimal cost/quality",
    capabilities: CLOUD_CAPS_FULL,
    freeTier: "Yes",
    tags: ["free", "aggregator", "routing"],
  },
  {
    id: "opencode-zen",
    name: "OpenCode Zen",
    category: "cloud",
    subcategory: "aggregator",
    sdkType: "openai",
    defaultBaseUrl: "https://opencode.ai/zen/v1",
    baseUrlEditable: false,
    authMethod: "bearer",
    apiKeyPlaceholder: "OpenCode Zen API key",
    apiKeyHelpUrl: "https://opencode.ai/auth",
    supportsModelDiscovery: true,
    defaultModels: [
      { id: "claude-sonnet-4-6", name: "Claude Sonnet 4.6", contextWindow: 200_000, supportsTools: true, supportsVision: true, tier: "powerful" },
      { id: "gpt-5.4", name: "GPT 5.4", contextWindow: 272_000, supportsTools: true, supportsVision: true, tier: "powerful" },
      { id: "gemini-3.1-pro", name: "Gemini 3.1 Pro", contextWindow: 200_000, supportsTools: true, supportsVision: true, tier: "balanced" },
      { id: "kimi-k2.6", name: "Kimi K2.6", contextWindow: 128_000, supportsTools: true, supportsVision: false, tier: "balanced" },
    ],
    icon: "opencode",
    description: "Curated, benchmarked AI models optimized for coding agents — pay as you go",
    capabilities: CLOUD_CAPS_FULL,
    freeTier: "5 free models",
    tags: ["free", "aggregator", "coding", "popular"],
  },
  {
    id: "opencode-go",
    name: "OpenCode Go",
    category: "cloud",
    subcategory: "aggregator",
    sdkType: "openai",
    defaultBaseUrl: "https://opencode.ai/zen/go/v1",
    baseUrlEditable: false,
    authMethod: "bearer",
    apiKeyPlaceholder: "OpenCode Go API key",
    apiKeyHelpUrl: "https://opencode.ai/auth",
    supportsModelDiscovery: true,
    defaultModels: [
      { id: "kimi-k2.6", name: "Kimi K2.6", contextWindow: 128_000, supportsTools: true, supportsVision: false, tier: "balanced" },
      { id: "glm-5.1", name: "GLM 5.1", contextWindow: 128_000, supportsTools: true, supportsVision: false, tier: "powerful" },
      { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro", contextWindow: 128_000, supportsTools: true, supportsVision: false, tier: "powerful" },
      { id: "qwen3.6-plus", name: "Qwen3.6 Plus", contextWindow: 128_000, supportsTools: true, supportsVision: false, tier: "balanced" },
    ],
    icon: "opencode",
    description: "Low-cost open coding models — $5 first month, then $10/mo",
    capabilities: CLOUD_CAPS_FULL,
    tags: ["aggregator", "cheap", "coding"],
  },

  // ═══════════════════════════════════════════════════════════
] as const satisfies readonly ProviderPreset[];

export { CLOUD_CAPS_FULL, CLOUD_CAPS_NO_VISION, LOCAL_CAPS_FULL, LOCAL_CAPS_MINIMAL };