import type { ProviderPreset } from "./provider-types";
import { LOCAL_CAPS_FULL, LOCAL_CAPS_MINIMAL } from "./provider-data-cloud-major";


export const LOCAL_PROVIDERS = [
  // Local Engines — Primary (7)
  // ═══════════════════════════════════════════════════════════
  {
    id: "ollama",
    name: "Ollama",
    category: "local",
    subcategory: "primary",
    sdkType: "openai",
    defaultBaseUrl: "http://localhost:11434/v1",
    baseUrlEditable: true,
    authMethod: "none",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "ollama",
    description: "Run LLMs locally with one command — most popular local engine",
    capabilities: LOCAL_CAPS_FULL,
    warnings: [
      "Streaming + tool calling broken on /v1. Use stream: false with tools",
      "tool_choice parameter NOT supported",
    ],
    defaultTimeoutMs: 300_000,
    tags: ["local", "popular", "easy"],
  },
  {
    id: "lm-studio",
    name: "LM Studio",
    category: "local",
    subcategory: "primary",
    sdkType: "openai",
    defaultBaseUrl: "http://localhost:1234/v1",
    baseUrlEditable: true,
    authMethod: "none",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "lmstudio",
    description: "Desktop app to discover, download, and run local LLMs",
    capabilities: LOCAL_CAPS_FULL,
    tags: ["local", "popular", "desktop"],
  },
  {
    id: "vllm",
    name: "vLLM",
    category: "local",
    subcategory: "primary",
    sdkType: "openai",
    defaultBaseUrl: "http://localhost:8000/v1",
    baseUrlEditable: true,
    authMethod: "none",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "vllm",
    description: "High-throughput LLM serving with PagedAttention",
    capabilities: LOCAL_CAPS_FULL,
    tags: ["local", "popular", "fast", "production"],
  },
  {
    id: "llama-cpp",
    name: "llama.cpp",
    category: "local",
    subcategory: "primary",
    sdkType: "openai",
    defaultBaseUrl: "http://localhost:8080/v1",
    baseUrlEditable: true,
    authMethod: "none",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "llamacpp",
    description: "C/C++ LLM inference with minimal dependencies",
    capabilities: LOCAL_CAPS_FULL,
    tags: ["local", "popular", "lightweight", "cpp"],
  },
  {
    id: "jan",
    name: "Jan",
    category: "local",
    subcategory: "primary",
    sdkType: "openai",
    defaultBaseUrl: "http://localhost:1337/v1",
    baseUrlEditable: true,
    authMethod: "none",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "jan",
    description: "Open-source desktop AI assistant with local model support",
    capabilities: LOCAL_CAPS_FULL,
    tags: ["local", "desktop", "easy"],
  },
  {
    id: "localai",
    name: "LocalAI",
    category: "local",
    subcategory: "primary",
    sdkType: "openai",
    defaultBaseUrl: "http://localhost:8080/v1",
    baseUrlEditable: true,
    authMethod: "none",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "localai",
    description: "Drop-in OpenAI replacement running locally with various backends",
    capabilities: LOCAL_CAPS_FULL,
    tags: ["local", "self-hosted", "multi-backend"],
  },
  {
    id: "gpt4all",
    name: "GPT4All",
    category: "local",
    subcategory: "primary",
    sdkType: "openai",
    defaultBaseUrl: "http://localhost:4891/v1",
    baseUrlEditable: true,
    authMethod: "none",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "gpt4all",
    description: "Privacy-first local AI — runs on consumer hardware",
    capabilities: LOCAL_CAPS_MINIMAL,
    warnings: ["No tool calling, no vision — most limited of primary engines"],
    tags: ["local", "privacy", "easy"],
  },

  // ═══════════════════════════════════════════════════════════
  // Local Engines — Secondary (12)
  // ═══════════════════════════════════════════════════════════
  {
    id: "text-generation-webui",
    name: "text-generation-webui",
    category: "local",
    subcategory: "secondary",
    sdkType: "openai",
    defaultBaseUrl: "http://localhost:5000/v1",
    baseUrlEditable: true,
    authMethod: "none",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "textgen",
    description: "Gradio web UI for running large language models",
    capabilities: LOCAL_CAPS_FULL,
    tags: ["local", "webui"],
  },
  {
    id: "koboldcpp",
    name: "KoboldCpp",
    category: "local",
    subcategory: "secondary",
    sdkType: "openai",
    defaultBaseUrl: "http://localhost:5001/v1",
    baseUrlEditable: true,
    authMethod: "none",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "koboldcpp",
    description: "Easy-to-use GGUF runner with built-in web UI",
    capabilities: LOCAL_CAPS_FULL,
    tags: ["local", "gguf", "easy"],
  },
  {
    id: "tgi",
    name: "TGI (HuggingFace)",
    category: "local",
    subcategory: "secondary",
    sdkType: "openai",
    defaultBaseUrl: "http://localhost:8080/v1",
    baseUrlEditable: true,
    authMethod: "none",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "huggingface",
    description: "Text Generation Inference by HuggingFace",
    capabilities: LOCAL_CAPS_FULL,
    warnings: ["Maintenance mode since Dec 2025. HuggingFace recommends vLLM or SGLang"],
    tags: ["local", "deprecated"],
  },
  {
    id: "tabbyml",
    name: "TabbyML",
    category: "local",
    subcategory: "secondary",
    sdkType: "openai",
    defaultBaseUrl: "http://localhost:8080/v1",
    baseUrlEditable: true,
    authMethod: "none",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "tabbyml",
    description: "Self-hosted AI coding assistant",
    capabilities: LOCAL_CAPS_FULL,
    warnings: ["Code completion focused, not general-purpose LLM server"],
    tags: ["local", "coding"],
  },
  {
    id: "llamafile",
    name: "llamafile (Mozilla)",
    category: "local",
    subcategory: "secondary",
    sdkType: "openai",
    defaultBaseUrl: "http://localhost:8080/v1",
    baseUrlEditable: true,
    authMethod: "none",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "mozilla",
    description: "Single-file executable LLMs by Mozilla",
    capabilities: LOCAL_CAPS_FULL,
    tags: ["local", "portable", "single-file"],
  },
  {
    id: "cortex",
    name: "Cortex (by Jan)",
    category: "local",
    subcategory: "secondary",
    sdkType: "openai",
    defaultBaseUrl: "http://localhost:7331/v1",
    baseUrlEditable: true,
    authMethod: "none",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "cortex",
    description: "Local AI engine from the Jan team — multi-engine support",
    capabilities: LOCAL_CAPS_FULL,
    tags: ["local", "multi-engine"],
  },
  {
    id: "docker-model-runner",
    name: "Docker Model Runner",
    category: "local",
    subcategory: "secondary",
    sdkType: "openai",
    defaultBaseUrl: "http://localhost:12434/engines/v1",
    baseUrlEditable: true,
    authMethod: "none",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "docker",
    description: "Run LLMs as Docker containers with built-in GPU support",
    capabilities: LOCAL_CAPS_FULL,
    tags: ["local", "docker", "containers"],
  },
  {
    id: "lmdeploy",
    name: "LMDeploy",
    category: "local",
    subcategory: "secondary",
    sdkType: "openai",
    defaultBaseUrl: "http://localhost:23333/v1",
    baseUrlEditable: true,
    authMethod: "none",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "lmdeploy",
    description: "Efficient LLM deployment toolkit from Shanghai AI Lab",
    capabilities: LOCAL_CAPS_FULL,
    tags: ["local", "deployment"],
  },
  {
    id: "sglang",
    name: "SGLang",
    category: "local",
    subcategory: "secondary",
    sdkType: "openai",
    defaultBaseUrl: "http://localhost:30000/v1",
    baseUrlEditable: true,
    authMethod: "none",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "sglang",
    description: "Fast serving framework for large language and vision models",
    capabilities: LOCAL_CAPS_FULL,
    tags: ["local", "fast", "production"],
  },
  {
    id: "tabbyapi",
    name: "TabbyAPI (ExLlamaV2)",
    category: "local",
    subcategory: "secondary",
    sdkType: "openai",
    defaultBaseUrl: "http://localhost:5000/v1",
    baseUrlEditable: true,
    authMethod: "none",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "tabbyapi",
    description: "ExLlamaV2-based API server for fast GPTQ/EXL2 inference",
    capabilities: LOCAL_CAPS_FULL,
    tags: ["local", "exllama", "quantized"],
  },
  {
    id: "mlc-llm",
    name: "MLC LLM",
    category: "local",
    subcategory: "secondary",
    sdkType: "openai",
    defaultBaseUrl: "http://localhost:8000/v1",
    baseUrlEditable: true,
    authMethod: "none",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "mlc",
    description: "Machine Learning Compilation for universal LLM deployment",
    capabilities: LOCAL_CAPS_FULL,
    tags: ["local", "compilation", "cross-platform"],
  },
  {
    id: "aphrodite",
    name: "Aphrodite Engine",
    category: "local",
    subcategory: "secondary",
    sdkType: "openai",
    defaultBaseUrl: "http://localhost:2242/v1",
    baseUrlEditable: true,
    authMethod: "none",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "aphrodite",
    description: "High-performance inference engine (vLLM fork) for roleplay and creative use",
    capabilities: LOCAL_CAPS_FULL,
    tags: ["local", "vllm-fork", "creative"],
  },

  // ═══════════════════════════════════════════════════════════
  // Local Frontends (3)
  // ═══════════════════════════════════════════════════════════
  {
    id: "msty",
    name: "Msty",
    category: "local",
    subcategory: "frontend",
    sdkType: "openai",
    defaultBaseUrl: "http://localhost:10000/v1",
    baseUrlEditable: true,
    authMethod: "none",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "msty",
    description: "Desktop AI chat app with local and cloud model support",
    capabilities: LOCAL_CAPS_FULL,
    tags: ["local", "desktop", "frontend"],
  },
  {
    id: "open-webui",
    name: "Open WebUI",
    category: "local",
    subcategory: "frontend",
    sdkType: "openai",
    defaultBaseUrl: "http://localhost:3000/v1",
    baseUrlEditable: true,
    authMethod: "none",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "openwebui",
    description: "Self-hosted web UI for local and remote LLMs",
    capabilities: LOCAL_CAPS_FULL,
    tags: ["local", "webui", "frontend"],
  },
  {
    id: "librechat",
    name: "LibreChat",
    category: "local",
    subcategory: "frontend",
    sdkType: "openai",
    defaultBaseUrl: "http://localhost:3080",
    baseUrlEditable: true,
    authMethod: "none",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "librechat",
    description: "Open-source ChatGPT-like UI supporting multiple providers",
    capabilities: LOCAL_CAPS_FULL,
    tags: ["local", "webui", "frontend", "multi-provider"],
  },
] as const satisfies readonly ProviderPreset[];