import type { ProviderPreset } from "./provider-types";
import { CLOUD_CAPS_FULL } from "./provider-data-cloud-major";

export const CLOUD_REGIONAL_PROVIDERS = [
  // Tier 4 — Regional / Emerging (12)
  // ═══════════════════════════════════════════════════════════
  {
    id: "moonshot",
    name: "Moonshot / Kimi",
    category: "cloud",
    subcategory: "regional",
    sdkType: "openai",
    defaultBaseUrl: "https://api.moonshot.ai/v1",
    baseUrlEditable: false,
    authMethod: "bearer",
    apiKeyPlaceholder: "Moonshot API key",
    apiKeyHelpUrl: "https://platform.moonshot.cn/",
    supportsModelDiscovery: true,
    defaultModels: [
      { id: "kimi-k2.6", name: "Kimi K2.6", contextWindow: 262_000, supportsTools: true, supportsVision: false, tier: "balanced" },
    ],
    icon: "moonshot",
    description: "Kimi K2.6 (262k ctx) — long-context autonomous agent model from Moonshot AI",
    capabilities: CLOUD_CAPS_FULL,
    tags: ["china", "long-context"],
  },
  {
    id: "dashscope",
    name: "Alibaba / DashScope",
    category: "cloud",
    subcategory: "regional",
    sdkType: "openai",
    defaultBaseUrl: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
    baseUrlEditable: false,
    authMethod: "bearer",
    apiKeyPrefix: "sk-",
    apiKeyPlaceholder: "sk-...",
    apiKeyHelpUrl: "https://dashscope.console.aliyun.com/",
    supportsModelDiscovery: true,
    defaultModels: [
      { id: "qwen-3.6-plus", name: "Qwen 3.6 Plus", contextWindow: 1_000_000, supportsTools: true, supportsVision: false, tier: "balanced" },
    ],
    icon: "alibaba",
    description: "Qwen 3.6 Plus (1M ctx) and other models via Alibaba DashScope",
    capabilities: CLOUD_CAPS_FULL,
    tags: ["china", "qwen"],
  },
  {
    id: "zhipu",
    name: "Zhipu AI / GLM",
    category: "cloud",
    subcategory: "regional",
    sdkType: "openai",
    defaultBaseUrl: "https://open.bigmodel.cn/api/paas/v4",
    baseUrlEditable: false,
    authMethod: "bearer",
    apiKeyPlaceholder: "Zhipu API key",
    apiKeyHelpUrl: "https://open.bigmodel.cn/",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "zhipu",
    description: "GLM models from Zhipu AI (Tsinghua-backed)",
    capabilities: CLOUD_CAPS_FULL,
    tags: ["china", "glm"],
  },
  {
    id: "baidu-qianfan",
    name: "Baidu Qianfan",
    category: "cloud",
    subcategory: "regional",
    sdkType: "openai",
    defaultBaseUrl: "https://qianfan.baidubce.com/v2",
    baseUrlEditable: false,
    authMethod: "aws-sig",
    apiKeyPlaceholder: "Baidu AK/SK",
    apiKeyHelpUrl: "https://cloud.baidu.com/product/wenxinworkshop",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "baidu",
    description: "ERNIE and other models via Baidu Qianfan",
    capabilities: CLOUD_CAPS_FULL,
    tags: ["china", "ernie"],
  },
  {
    id: "volcengine",
    name: "Volcengine / Doubao",
    category: "cloud",
    subcategory: "regional",
    sdkType: "openai",
    defaultBaseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    baseUrlEditable: false,
    authMethod: "bearer",
    apiKeyPlaceholder: "Volcengine API key",
    apiKeyHelpUrl: "https://www.volcengine.com/",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "volcengine",
    description: "Doubao models from ByteDance's Volcengine",
    capabilities: CLOUD_CAPS_FULL,
    tags: ["china", "doubao"],
  },
  {
    id: "minimax",
    name: "MiniMax",
    category: "cloud",
    subcategory: "regional",
    sdkType: "openai",
    defaultBaseUrl: "https://api.minimax.io/v1",
    baseUrlEditable: true,
    authMethod: "bearer",
    apiKeyPlaceholder: "MiniMax API key (sk-cp-… for Coding/Token Plan)",
    apiKeyHelpUrl: "https://platform.minimax.io/user-center/payment/token-plan",
    // MiniMax does not expose GET /v1/models — fall back to defaults / chat ping.
    supportsModelDiscovery: false,
    defaultModels: [
      { id: "MiniMax-M2.7", name: "MiniMax M2.7", contextWindow: 204_800, supportsTools: true, supportsVision: false, tier: "powerful" },
      { id: "MiniMax-M2.7-highspeed", name: "MiniMax M2.7 (high-speed)", contextWindow: 204_800, supportsTools: true, supportsVision: false, tier: "fast" },
      { id: "MiniMax-M2.5", name: "MiniMax M2.5", contextWindow: 196_608, supportsTools: true, supportsVision: false, tier: "balanced" },
    ],
    icon: "minimax",
    description: "MiniMax M2.7 (205k ctx) and M2.5 — strong coding & agent models",
    capabilities: CLOUD_CAPS_FULL,
    tags: ["china", "multimodal", "coding", "popular"],
  },
  {
    id: "stepfun",
    name: "StepFun",
    category: "cloud",
    subcategory: "regional",
    sdkType: "openai",
    defaultBaseUrl: "https://api.stepfun.ai/v1",
    baseUrlEditable: false,
    authMethod: "bearer",
    apiKeyPlaceholder: "StepFun API key",
    apiKeyHelpUrl: "https://platform.stepfun.com/",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "stepfun",
    description: "Step models with strong reasoning capabilities",
    capabilities: CLOUD_CAPS_FULL,
    tags: ["china", "reasoning"],
  },
  {
    id: "01ai",
    name: "01.AI / Yi",
    category: "cloud",
    subcategory: "regional",
    sdkType: "openai",
    defaultBaseUrl: "https://api.01.ai/v1",
    baseUrlEditable: false,
    authMethod: "bearer",
    apiKeyPlaceholder: "01.AI API key",
    apiKeyHelpUrl: "https://platform.01.ai/",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "01ai",
    description: "Yi series models from Kai-Fu Lee's 01.AI",
    capabilities: CLOUD_CAPS_FULL,
    tags: ["china", "yi"],
  },
  {
    id: "tencent-hunyuan",
    name: "Tencent Hunyuan",
    category: "cloud",
    subcategory: "regional",
    sdkType: "openai",
    defaultBaseUrl: "https://api.hunyuan.cloud.tencent.com/v1",
    baseUrlEditable: false,
    authMethod: "bearer",
    apiKeyPlaceholder: "Tencent Hunyuan API key",
    apiKeyHelpUrl: "https://cloud.tencent.com/product/hunyuan",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "tencent",
    description: "Hunyuan large language models from Tencent",
    capabilities: CLOUD_CAPS_FULL,
    tags: ["china", "hunyuan"],
  },
  {
    id: "cerebras",
    name: "Cerebras",
    category: "cloud",
    subcategory: "regional",
    sdkType: "openai",
    defaultBaseUrl: "https://api.cerebras.ai/v1",
    baseUrlEditable: false,
    authMethod: "bearer",
    apiKeyPlaceholder: "Cerebras API key",
    apiKeyHelpUrl: "https://cloud.cerebras.ai/",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "cerebras",
    description: "Wafer-scale AI chips with ultra-fast inference",
    capabilities: CLOUD_CAPS_FULL,
    freeTier: "1M tokens/day free",
    tags: ["free", "fast"],
  },
  {
    id: "ai21",
    name: "AI21 Labs",
    category: "cloud",
    subcategory: "regional",
    sdkType: "openai",
    defaultBaseUrl: "https://api.ai21.com/studio/v1",
    baseUrlEditable: false,
    authMethod: "bearer",
    apiKeyPlaceholder: "AI21 API key",
    apiKeyHelpUrl: "https://studio.ai21.com/account/api-key",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "ai21",
    description: "Jamba and Jurassic models from AI21 Labs",
    capabilities: CLOUD_CAPS_FULL,
    tags: ["enterprise", "jamba"],
  },
  {
    id: "hyperbolic",
    name: "Hyperbolic",
    category: "cloud",
    subcategory: "regional",
    sdkType: "openai",
    defaultBaseUrl: "https://api.hyperbolic.xyz/v1",
    baseUrlEditable: false,
    authMethod: "bearer",
    apiKeyPlaceholder: "Hyperbolic API key",
    apiKeyHelpUrl: "https://app.hyperbolic.xyz/",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "hyperbolic",
    description: "Decentralized AI compute marketplace",
    capabilities: CLOUD_CAPS_FULL,
    tags: ["decentralized"],
  },

  // ═══════════════════════════════════════════════════════════
  // Tier 5 — Infrastructure (8)
  // ═══════════════════════════════════════════════════════════
  {
    id: "deepinfra",
    name: "DeepInfra",
    category: "cloud",
    subcategory: "infrastructure",
    sdkType: "openai",
    defaultBaseUrl: "https://api.deepinfra.com/v1/openai",
    baseUrlEditable: false,
    authMethod: "bearer",
    apiKeyPlaceholder: "DeepInfra API key",
    apiKeyHelpUrl: "https://deepinfra.com/dash/api_keys",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "deepinfra",
    description: "Serverless inference for popular open-source models",
    capabilities: CLOUD_CAPS_FULL,
    tags: ["infrastructure", "open-source"],
  },
  {
    id: "nvidia-nim",
    name: "NVIDIA NIM",
    category: "cloud",
    subcategory: "infrastructure",
    sdkType: "openai",
    defaultBaseUrl: "https://integrate.api.nvidia.com/v1",
    baseUrlEditable: false,
    authMethod: "bearer",
    apiKeyPrefix: "nvapi-",
    apiKeyPlaceholder: "nvapi-...",
    apiKeyHelpUrl: "https://build.nvidia.com/",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "nvidia",
    description: "NVIDIA-optimized model inference microservices",
    capabilities: CLOUD_CAPS_FULL,
    tags: ["infrastructure", "nvidia"],
  },
  {
    id: "cloudflare-ai",
    name: "Cloudflare Workers AI",
    category: "cloud",
    subcategory: "infrastructure",
    sdkType: "openai",
    defaultBaseUrl: "https://api.cloudflare.com/client/v4/accounts/{id}/ai/v1",
    baseUrlEditable: true,
    baseUrlTemplate: true,
    authMethod: "bearer",
    apiKeyPlaceholder: "Cloudflare API token",
    apiKeyHelpUrl: "https://dash.cloudflare.com/profile/api-tokens",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "cloudflare",
    description: "Run AI models on Cloudflare's global edge network",
    capabilities: CLOUD_CAPS_FULL,
    tags: ["infrastructure", "edge"],
  },
  {
    id: "nebius",
    name: "Nebius AI Studio",
    category: "cloud",
    subcategory: "infrastructure",
    sdkType: "openai",
    defaultBaseUrl: "https://api.studio.nebius.ai/v1",
    baseUrlEditable: false,
    authMethod: "bearer",
    apiKeyPlaceholder: "Nebius API key",
    apiKeyHelpUrl: "https://studio.nebius.ai/",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "nebius",
    description: "European AI cloud with GPU infrastructure",
    capabilities: CLOUD_CAPS_FULL,
    tags: ["infrastructure", "european"],
  },
  {
    id: "scaleway",
    name: "Scaleway",
    category: "cloud",
    subcategory: "infrastructure",
    sdkType: "openai",
    defaultBaseUrl: "https://api.scaleway.ai/v1",
    baseUrlEditable: false,
    authMethod: "bearer",
    apiKeyPlaceholder: "Scaleway API key",
    apiKeyHelpUrl: "https://console.scaleway.com/",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "scaleway",
    description: "French cloud provider with AI inference endpoints",
    capabilities: CLOUD_CAPS_FULL,
    tags: ["infrastructure", "european"],
  },
  {
    id: "infermatic",
    name: "Infermatic",
    category: "cloud",
    subcategory: "infrastructure",
    sdkType: "openai",
    defaultBaseUrl: "https://api.totalgpt.ai",
    baseUrlEditable: false,
    authMethod: "bearer",
    apiKeyPlaceholder: "Infermatic API key",
    apiKeyHelpUrl: "https://infermatic.ai/",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "infermatic",
    description: "Budget-friendly AI inference platform",
    capabilities: CLOUD_CAPS_FULL,
    tags: ["infrastructure", "cheap"],
  },
  {
    id: "lepton-ai",
    name: "Lepton AI",
    category: "cloud",
    subcategory: "infrastructure",
    sdkType: "openai",
    defaultBaseUrl: "https://{model}.lepton.run/api/v1",
    baseUrlEditable: true,
    baseUrlTemplate: true,
    authMethod: "bearer",
    apiKeyPlaceholder: "Lepton API key",
    apiKeyHelpUrl: "https://www.lepton.ai/",
    supportsModelDiscovery: false,
    defaultModels: [],
    icon: "lepton",
    description: "Serverless AI platform with per-model endpoints",
    capabilities: CLOUD_CAPS_FULL,
    tags: ["infrastructure", "serverless"],
  },
  {
    id: "ovhcloud",
    name: "OVHcloud",
    category: "cloud",
    subcategory: "infrastructure",
    sdkType: "openai",
    defaultBaseUrl: "https://endpoints.ai.cloud.ovh.net",
    baseUrlEditable: false,
    authMethod: "bearer",
    apiKeyPlaceholder: "OVHcloud API key",
    apiKeyHelpUrl: "https://www.ovhcloud.com/en/public-cloud/ai-endpoints/",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "ovhcloud",
    description: "European cloud with sovereign AI endpoints",
    capabilities: CLOUD_CAPS_FULL,
    tags: ["infrastructure", "european", "sovereign"],
  },

  // ═══════════════════════════════════════════════════════════
] as const satisfies readonly ProviderPreset[];