apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: doable
  annotations:
    # Minor routing optimization: prefer pods in the same topology zone.
    service.kubernetes.io/topology-aware-hints: auto
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
