import type { IntegrationDefinition } from "../types.js";

const ATLASSIAN_AUTH_URL = "https://auth.atlassian.com/authorize";
const ATLASSIAN_TOKEN_URL = "https://auth.atlassian.com/oauth/token";

export const PRODUCTIVITY_PART2: Record<string, IntegrationDefinition> = {

  baserow: {
    id: "baserow",
    piecePackage: "@activepieces/piece-baserow",
    displayName: "Baserow",
    description: "Create, list, update, and delete rows in Baserow databases.",
    logoUrl: "https://cdn.activepieces.com/pieces/baserow.png",
    category: "productivity",
    tags: ["database", "open-source", "nocode", "airtable-alternative"],
    authType: "secret_text",
    actions: ["create_row", "upsert_row", "update_row", "delete_row"],
    tier: "community",
    requiresOAuthApp: false,
    supportsUserProvidedCredentials: true,
  },

  nocodb: {
    id: "nocodb",
    piecePackage: "@activepieces/piece-nocodb",
    displayName: "NocoDB",
    description: "Create, list, and update records in NocoDB databases.",
    logoUrl: "https://cdn.activepieces.com/pieces/nocodb.png",
    category: "productivity",
    tags: ["database", "open-source", "nocode", "airtable-alternative"],
    authType: "secret_text",
    actions: ["create_record", "find_record", "update_record"],
    tier: "community",
    requiresOAuthApp: false,
    supportsUserProvidedCredentials: true,
  },

  // ── Project Management ────────────────────────────────

  linear: {
    id: "linear",
    piecePackage: "@activepieces/piece-linear",
    displayName: "Linear",
    description: "Create issues, list teams, and manage projects in Linear.",
    logoUrl: "https://cdn.activepieces.com/pieces/linear.png",
    category: "project_management",
    tags: ["issues", "project-management", "engineering", "agile"],
    authType: "oauth2",
    oauth2Config: {
      authUrl: "https://linear.app/oauth/authorize",
      tokenUrl: "https://api.linear.app/oauth/token",
      scopes: ["read", "write"],
    },
    actions: ["create_issue", "update_issue", "find_issue", "create_comment", "list_teams"],
    tier: "built_in",
    requiresOAuthApp: true,
    supportsUserProvidedCredentials: true,
  },

  jira_cloud: {
    id: "jira_cloud",
    piecePackage: "@activepieces/piece-jira-cloud",
    displayName: "Jira Cloud",
    description: "Create and search issues, add comments, and manage projects in Jira.",
    logoUrl: "https://cdn.activepieces.com/pieces/jira.png",
    category: "project_management",
    tags: ["issues", "project-management", "agile", "atlassian"],
    authType: "oauth2",
    oauth2Config: {
      authUrl: ATLASSIAN_AUTH_URL,
      tokenUrl: ATLASSIAN_TOKEN_URL,
      scopes: ["read:jira-work", "write:jira-work"],
    },
    actions: ["create_issue", "update_issue", "search_issues", "add_comment", "list_projects"],
    tier: "built_in",
    requiresOAuthApp: true,
    supportsUserProvidedCredentials: true,
  },

  confluence: {
    id: "confluence",
    piecePackage: "@activepieces/piece-confluence",
    displayName: "Confluence",
    description: "Create pages, search content, and manage knowledge bases in Confluence.",
    logoUrl: "https://cdn.activepieces.com/pieces/confluence.png",
    category: "project_management",
    tags: ["wiki", "docs", "knowledge-base", "atlassian"],
    authType: "oauth2",
    oauth2Config: {
      authUrl: ATLASSIAN_AUTH_URL,
      tokenUrl: ATLASSIAN_TOKEN_URL,
      scopes: ["read:confluence-content.all", "write:confluence-content"],
    },
    actions: ["create_page", "update_page", "getPageContent", "get_page"],
    tier: "built_in",
    requiresOAuthApp: true,
    supportsUserProvidedCredentials: true,
  },

  productboard: {
    id: "productboard",
    piecePackage: "@activepieces/piece-productboard",
    displayName: "Productboard",
    description: "Create notes and manage features in Productboard.",
    logoUrl: "https://cdn.activepieces.com/pieces/productboard.png",
    category: "project_management",
    tags: ["product", "roadmap", "features", "feedback"],
    authType: "secret_text",
    actions: ["create_note", "list_features", "create_feature"],
    tier: "community",
    requiresOAuthApp: false,
    supportsUserProvidedCredentials: true,
  },

  // ── Time Tracking ─────────────────────────────────────

  clockify: {
    id: "clockify",
    piecePackage: "@activepieces/piece-clockify",
    displayName: "Clockify",
    description: "Create time entries and list projects in Clockify.",
    logoUrl: "https://cdn.activepieces.com/pieces/clockify.png",
    category: "project_management",
    tags: ["time-tracking", "timesheets", "productivity"],
    authType: "secret_text",
    actions: ["create_time_entry", "find-time-entry", "list_projects"],
    tier: "community",
    requiresOAuthApp: false,
    supportsUserProvidedCredentials: true,
  },

  everhour: {
    id: "everhour",
    piecePackage: "@activepieces/piece-everhour",
    displayName: "Everhour",
    description: "Track time and list tasks in Everhour.",
    logoUrl: "https://cdn.activepieces.com/pieces/everhour.png",
    category: "project_management",
    tags: ["time-tracking", "timesheets", "budgeting"],
    authType: "secret_text",
    actions: ["create_time_entry", "list_tasks"],
    tier: "community",
    requiresOAuthApp: false,
    supportsUserProvidedCredentials: true,
  },

  harvest: {
    id: "harvest",
    piecePackage: "@activepieces/piece-harvest",
    displayName: "Harvest",
    description: "Create and list time entries in Harvest.",
    logoUrl: "https://cdn.activepieces.com/pieces/harvest.png",
    category: "project_management",
    tags: ["time-tracking", "invoicing", "timesheets"],
    authType: "secret_text",
    actions: ["create_time_entry", "get_time_entries"],
    tier: "community",
    requiresOAuthApp: false,
    supportsUserProvidedCredentials: true,
  },

  toggl_track: {
    id: "toggl_track",
    piecePackage: "@activepieces/piece-toggl-track",
    displayName: "Toggl Track",
    description: "Create time entries and list projects in Toggl Track.",
    logoUrl: "https://cdn.activepieces.com/pieces/toggl.png",
    category: "project_management",
    tags: ["time-tracking", "timesheets", "productivity"],
    authType: "secret_text",
    actions: ["create_time_entry", "list_time_entries", "list_projects"],
    tier: "community",
    requiresOAuthApp: false,
    supportsUserProvidedCredentials: true,
  },

  // ── Task Management ───────────────────────────────────

  ticktick: {
    id: "ticktick",
    piecePackage: "@activepieces/piece-ticktick",
    displayName: "TickTick",
    description: "Create, list, and complete tasks in TickTick.",
    logoUrl: "https://cdn.activepieces.com/pieces/ticktick.png",
    category: "productivity",
    tags: ["tasks", "todo", "habits", "personal-productivity"],
    authType: "secret_text",
    actions: ["create_task", "list_tasks", "complete_task"],
    tier: "community",
    requiresOAuthApp: false,
    supportsUserProvidedCredentials: true,
  },

  meistertask: {
    id: "meistertask",
    piecePackage: "@activepieces/piece-meistertask",
    displayName: "MeisterTask",
    description: "Create, list, and update tasks in MeisterTask.",
    logoUrl: "https://cdn.activepieces.com/pieces/meistertask.png",
    category: "productivity",
    tags: ["tasks", "kanban", "project-management"],
    authType: "secret_text",
    actions: ["create_task", "list_tasks", "update_task"],
    tier: "community",
    requiresOAuthApp: false,
    supportsUserProvidedCredentials: true,
  },

  taskade: {
    id: "taskade",
    piecePackage: "@activepieces/piece-taskade",
    displayName: "Taskade",
    description: "Create and list tasks in Taskade workspaces.",
    logoUrl: "https://cdn.activepieces.com/pieces/taskade.png",
    category: "productivity",
    tags: ["tasks", "collaboration", "notes", "ai"],
    authType: "secret_text",
    actions: ["create_task", "list_tasks"],
    tier: "community",
    requiresOAuthApp: false,
    supportsUserProvidedCredentials: true,
  },

  nifty: {
    id: "nifty",
    piecePackage: "@activepieces/piece-nifty",
    displayName: "Nifty",
    description: "Create and list tasks in Nifty project management.",
    logoUrl: "https://cdn.activepieces.com/pieces/nifty.png",
    category: "productivity",
    tags: ["project-management", "tasks", "collaboration"],
    authType: "secret_text",
    actions: ["create_task", "list_tasks"],
    tier: "community",
    requiresOAuthApp: false,
    supportsUserProvidedCredentials: true,
  },
};
