#!/bin/bash
# ╔══════════════════════════════════════════════════════════════════════╗
# ║  Doable — Build-time HTTP proxy installer (Squid on 127.0.0.1:3128) ║
# ║                                                                      ║
# ║  Called by deployment/server-setup.sh Step 12.5.                    ║
# ║  Installs Squid, writes an allow-list covering npm, PyPI, and        ║
# ║  common CDN hosts, then binds Squid to 127.0.0.1:3128 only.         ║
# ║                                                                      ║
# ║  Every sandboxed build (UID range 10001-65000) is blocked from       ║
# ║  direct egress by nft — this proxy is their only outbound path.      ║
# ║  The allow-list keeps AI-generated builds from phoning home to       ║
# ║  arbitrary hosts during npm install / pip install / pnpm fetch.      ║
# ╚══════════════════════════════════════════════════════════════════════╝
set -euo pipefail

info()  { echo "[setup-build-proxy] $*"; }
ok()    { echo "[setup-build-proxy] OK: $*"; }
warn()  { echo "[setup-build-proxy] WARN: $*"; }

# ── Install Squid ──────────────────────────────────────────────────────
if ! command -v squid &>/dev/null; then
  info "Installing squid..."
  apt-get install -y squid
fi

# ── Allow-list ─────────────────────────────────────────────────────────
# 15-host list covering npm, PyPI, GitHub releases, and common CDNs used
# by framework scaffolders. Expand conservatively — each addition widens
# the surface for supply-chain attacks from inside the sandbox.
mkdir -p /etc/squid/conf.d
cat > /etc/squid/conf.d/doable-allowlist.conf << 'SQUIDEOF'
# Doable build-time proxy allow-list
# Generated by scripts/setup-build-proxy.sh — edit here, not in squid.conf.

acl doable_build_allowed dstdomain \
  registry.npmjs.org \
  registry.yarnpkg.com \
  pypi.org \
  files.pythonhosted.org \
  github.com \
  objects.githubusercontent.com \
  raw.githubusercontent.com \
  releases.githubusercontent.com \
  codeload.github.com \
  api.github.com \
  nodejs.org \
  deb.nodesource.com \
  dl.cloudflare.com \
  cdn.jsdelivr.net \
  unpkg.com

http_access allow doable_build_allowed
SQUIDEOF

# ── Main squid.conf ────────────────────────────────────────────────────
# Overwrite the default config with a minimal, hardened one.
# Binds ONLY to 127.0.0.1 (CLAUDE.md: no 0.0.0.0).
# Includes the allow-list drop-in and denies everything else.
cat > /etc/squid/squid.conf << 'MAINCFGEOF'
# Doable build-time proxy — minimal hardened config
# Generated by scripts/setup-build-proxy.sh

# Bind to loopback only — all external access goes through Cloudflare Tunnel.
http_port 127.0.0.1:3128

# Include per-host allow-list (managed separately for easy extension).
include /etc/squid/conf.d/doable-allowlist.conf

# Deny CONNECT tunnelling except to standard HTTPS port.
acl CONNECT method CONNECT
acl SSL_ports port 443
http_access deny CONNECT !SSL_ports

# Allow localhost management queries from the doable API process.
acl localhost src 127.0.0.1/32
http_access allow localhost

# Deny everything not matched by the allow-list above.
http_access deny all

# Silence the access log for health-check noise; keep cache log.
access_log none
cache_log /var/log/squid/cache.log
cache_store_log none

# Tiny disk cache — builds benefit from package caching between runs.
cache_dir ufs /var/spool/squid 512 16 256
maximum_object_size 64 MB

# Strip identifying headers so npm/pip don't see the proxy hostname.
via off
forwarded_for delete
request_header_access X-Forwarded-For deny all
MAINCFGEOF

# ── Enable and start ───────────────────────────────────────────────────
systemctl enable squid
# `squid -k parse` validates config before we restart to catch typos.
if squid -k parse 2>/dev/null; then
  systemctl restart squid
  # Give Squid 5 s to fully bind before the smoke test.
  sleep 5
  if systemctl is-active squid >/dev/null 2>&1; then
    ok "Squid listening on 127.0.0.1:3128 (build proxy active)"
  else
    warn "Squid failed to start — check: journalctl -u squid -n 30"
    exit 1
  fi
else
  warn "squid -k parse reported config errors — see above. Squid not restarted."
  exit 1
fi

# ── Smoke test ─────────────────────────────────────────────────────────
# Verify the proxy can actually reach registry.npmjs.org through the allow-list.
if curl -fs -x http://127.0.0.1:3128 --max-time 10 \
    "https://registry.npmjs.org/" -o /dev/null 2>/dev/null; then
  ok "Smoke test passed: registry.npmjs.org reachable via proxy"
else
  warn "Smoke test failed: registry.npmjs.org not reachable via proxy. Check network + allow-list."
fi
