import type { FrameworkPrompt } from "./index.js";

/**
 * Next.js App Router framework prompt. NEW content (no parallel exists in
 * the legacy system-prompts.ts). Used when a project's framework_id is
 * "nextjs-app". Mirrors the section split of vite-react.ts so the same
 * renderFrameworkPrompt() concatenation works.
 */
export const nextjsAppPrompt: FrameworkPrompt = {
  systemIntro:
    "The project is a Next.js 15 App Router + React 19 + TypeScript app with Tailwind CSS v4 (via @tailwindcss/postcss). This is App Router (not the legacy Pages Router) and not Vite. Files are hot-reloaded via the Next.js dev server. The dev server runs in the project sandbox and the live preview shows the running app.",

  envConventions: [
    "0. **🔌 USE CONNECTED INTEGRATIONS**: If a `<connected-integrations>` block appears above, the user has already connected those services. You MUST reference the listed env vars and call the listed tools. NEVER ask the user to paste API keys, URLs, or tokens for any service in that block. If you need a service NOT in the block, call `request_integration` instead of asking for keys.",
    "",
    "0a. **ENV VAR PREFIX RULES (Next.js)**:",
    "   - Server-only secrets: read with `process.env.X` inside server components, server actions (`'use server'`), and route handlers (`app/api/*/route.ts`). NEVER expose these to the browser.",
    "   - Browser-safe values: must be prefixed with `NEXT_PUBLIC_` (e.g. `process.env.NEXT_PUBLIC_SUPABASE_URL`). Only `NEXT_PUBLIC_*` vars are inlined into the client bundle.",
    "   - NEVER put a service-role key, secret key, or password in a `NEXT_PUBLIC_*` var — it would ship to every visitor's browser.",
    "   - Do NOT use `import.meta.env` — that is Vite syntax. Next.js uses `process.env`.",
    "",
    "0a2. **🔌 INTEGRATION SDK (`@doable/sdk`)**: When the user wants to interact with external services (Slack, Stripe, Gmail, GitHub, etc.) from the generated app at runtime, use the `@doable/sdk` package. This SDK calls a secure server-side proxy — credentials never reach the browser.",
    "   **Server Actions (PREFERRED for mutations):**",
    "   ```ts",
    "   \"use server\";",
    "   import { createServerClient } from \"@doable/sdk/server\";",
    "   const doable = createServerClient();",
    "   export async function sendSlackMessage(channel: string, text: string) {",
    "     const result = await doable.integrations.run(\"slack\", \"send_channel_message\", { channel, text });",
    "     if (!result.success) throw new Error(result.error?.message);",
    "     return result.data;",
    "   }",
    "   ```",
    "   **Server Components (data fetching):**",
    "   ```ts",
    "   import { createServerClient } from \"@doable/sdk/server\";",
    "   const doable = createServerClient();",
    "   export default async function Page() {",
    "     const channels = await doable.integrations.run(\"slack\", \"list_channels\", {});",
    "     return <ul>{channels.data?.map((ch: any) => <li key={ch.id}>{ch.name}</li>)}</ul>;",
    "   }",
    "   ```",
    "   **Client Components (interactive UI):**",
    "   ```ts",
    "   \"use client\";",
    "   import { useIntegration } from \"@doable/sdk/react\";",
    "   const slack = useIntegration(\"slack\", \"send_channel_message\");",
    "   <button onClick={() => slack.run({ channel: \"#general\", text: \"Hi\" })}>Send</button>",
    "   ```",
    "   RULES:",
    "   - For mutations: ALWAYS prefer Server Actions with `createServerClient()`",
    "   - For data display: PREFER Server Components with `createServerClient()`",
    "   - For interactive UI needing integration data: use `useIntegration()` hook in client components",
    "   - NEVER fetch external APIs directly from client code (Slack API, Stripe API, etc.)",
    "   - NEVER hardcode API keys or tokens in the code",
    "   - Exception: Supabase — use the direct Supabase client SDK (its public keys are browser-safe)",
    "   - Add `@doable/sdk` to package.json dependencies: `\"@doable/sdk\": \"workspace:*\"`",
    "",
    "0b. **🔌 SUPABASE NOT CONNECTED? PROVISION FIRST**: If the user asks to add Supabase / a database but there is NO `supabase` entry in the `<connected-integrations>` block above (or the block is absent), you MUST call the `provision_supabase` tool BEFORE writing any code. The provision tool injects `SUPABASE_URL`, `SUPABASE_ANON_KEY`, `SUPABASE_SERVICE_ROLE_KEY`, and the `NEXT_PUBLIC_SUPABASE_*` mirrors automatically.",
    "",
    "1. **SUPABASE CLIENT PATTERNS (Next.js)**:",
    "   - Server-side (route handler / server action / server component): use the service-role key for trusted operations.",
    "     ```ts",
    "     // app/api/todos/route.ts",
    "     import { createClient } from \"@supabase/supabase-js\";",
    "     const supabase = createClient(",
    "       process.env.SUPABASE_URL!,",
    "       process.env.SUPABASE_SERVICE_ROLE_KEY!,",
    "     );",
    "     export async function GET() {",
    "       const { data, error } = await supabase.from(\"todos\").select(\"*\");",
    "       if (error) return Response.json({ error: error.message }, { status: 500 });",
    "       return Response.json(data);",
    "     }",
    "     ```",
    "   - Client-side ('use client' components): use the anon key via `NEXT_PUBLIC_*`.",
    "     ```ts",
    "     const url = process.env.NEXT_PUBLIC_SUPABASE_URL ?? \"\";",
    "     const key = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? \"\";",
    "     export const supabase = url ? createClient(url, key) : null;",
    "     ```",
    "     Components must check `if (!supabase)` and render a placeholder rather than crashing.",
  ].join("\n"),

  routing: [
    "2. **APP ROUTER FILE-BASED ROUTING**: Routing is determined by folders inside `app/`. Do NOT install `react-router-dom`, do NOT use `HashRouter` or `BrowserRouter` — Next.js handles routing automatically.",
    "   - `app/page.tsx` → `/`",
    "   - `app/about/page.tsx` → `/about`",
    "   - `app/blog/[slug]/page.tsx` → `/blog/:slug` (params arrive via the `params` prop)",
    "   - `app/layout.tsx` is the root layout (must render `<html>` and `<body>`).",
    "   - Nested `layout.tsx` files compose around their child pages.",
    "   - Route handlers (replaces API routes): `app/api/<name>/route.ts` exporting `GET`, `POST`, etc.",
    "   - Server actions: a function with the `\"use server\"` directive at the top of the file (or inline). Call them directly from client components — Next.js wires the RPC.",
    "   - For client-side navigation, use `<Link href=\"/path\">` from `next/link` and `useRouter()` from `next/navigation`. Do NOT use `<a href>` for internal links.",
    "   - The preview runs at the project's dev URL — Next.js handles base paths via `next.config.ts`. Do NOT manually prefix routes.",
    "",
    "**CRITICAL: Client-side fetch URLs MUST be RELATIVE**",
    "",
    "The Doable preview hosts your app inside an iframe at `/preview/<projectId>/`. An absolute fetch path like `fetch(\"/api/items\")` resolves to the iframe's ORIGIN root (Doable's API) — NOT your Next.js route. Your fetch will hit Doable's API and 404.",
    "",
    "ALWAYS use one of:",
    "1. Relative paths: `fetch(\"./api/items\")` (resolves to `/preview/<id>/api/items` and is forwarded to your Next.js dev server).",
    "2. basePath-aware: `` fetch(`${process.env.NEXT_PUBLIC_BASE_PATH ?? \"\"}/api/items`) ``",
    "3. Next.js's `useRouter().basePath` helper inside client components.",
    "",
    "NEVER write `fetch(\"/api/items\")` with a leading slash from a client component. Server-side code (route handlers, server actions, server components) is fine — it executes inside the Next.js server, not the browser.",
    "",
    "If you find yourself wanting `fetch(\"/api/...\")` for simplicity, switch to a server component or server action that runs the data load on the server side.",
  ].join("\n"),

  styling: [
    "6. **TAILWIND CSS v4 (Next.js)** — Tailwind v4 is wired through `@tailwindcss/postcss`, NOT `@tailwindcss/vite`:",
    "   - `app/globals.css` must start with `@import \"tailwindcss\";` as the FIRST line. Import it from `app/layout.tsx`.",
    "   - NEVER use `@tailwind base; @tailwind components; @tailwind utilities;` (v3 syntax — broken in v4).",
    "   - NEVER use `@apply` in CSS — it is removed by default in v4. Use utility classes directly in JSX.",
    "   - NEVER create a `tailwind.config.ts` / `tailwind.config.js` — v4 auto-detects utility classes.",
    "   - Custom theme values go in the `@theme` directive in `globals.css`:",
    "     ```css",
    "     @import \"tailwindcss\";",
    "     @theme {",
    "       --color-brand: #3b82f6;",
    "       --font-heading: \"Inter\", sans-serif;",
    "     }",
    "     ```",
    "   - Use them as classes: `className=\"text-brand font-heading\"`.",
  ].join("\n"),

  fileShape: [
    "7. **SERVER VS CLIENT COMPONENTS**:",
    "   - Files in `app/` are SERVER components by default — they can `await` data, read files, call any Node module, and use `process.env.SECRET_*` directly. They CANNOT use `useState`, `useEffect`, event handlers, or browser APIs.",
    "   - Add `\"use client\"` as the FIRST line of a file to make it a client component. Use this for interactive UI (forms, hooks, browser APIs).",
    "   - Push the `\"use client\"` boundary as deep as possible — keep layouts and data-fetching pages as server components.",
    "",
    "8. **ROUTE HANDLERS**: Files at `app/api/<name>/route.ts` export named HTTP-method functions:",
    "   ```ts",
    "   export async function GET(req: Request) { return Response.json({ ok: true }); }",
    "   export async function POST(req: Request) { const body = await req.json(); /* ... */ }",
    "   ```",
    "   Use these for any server-side endpoint (webhooks, third-party API proxies, secret-bearing fetches).",
    "",
    "9. **SERVER ACTIONS**: A function with `\"use server\"` runs on the server and is callable from a client component. Use them for form submissions and mutations instead of writing a route handler when the call only happens from your own UI.",
    "",
    "10. **FILE EXTENSIONS — CRITICAL**:",
    "    - `.tsx` = TypeScript with JSX (React components).",
    "    - `.ts`  = TypeScript without JSX (route handlers, utilities, configs).",
    "    - `.js`  = plain JavaScript ONLY. ABSOLUTELY NO TypeScript syntax inside (no `import type`, no `: NextConfig`, no interface declarations, no type parameters, no `as Type`).",
    "    - The blank template ships **`next.config.ts`** (TypeScript). To change Next config, EDIT THAT FILE — do NOT create `next.config.js` or `next.config.mjs` alongside it. Having both at once breaks the build because Next.js loads the .js variant and rejects `import type` syntax.",
    "    - Same rule for `postcss.config`: the template ships `postcss.config.js`. Edit it as plain JS — do NOT add a `.ts` variant.",
    "    - If you want to convert a config from .js to .ts (or vice-versa), DELETE the old file in the SAME tool call sequence — never leave both extensions for the same config.",
    "",
    "10b. **MANDATORY ROOT FILES** for every Next.js project — verify they exist before declaring done. If any are missing, create them in the same response:",
    "    - `next.config.ts` — the basePath wiring is REQUIRED for the Doable preview to work. Minimum content:",
    "      ```ts",
    "      import type { NextConfig } from \"next\";",
    "      const basePath = process.env.DOABLE_BASE_PATH && process.env.DOABLE_BASE_PATH !== \"/\"",
    "        ? process.env.DOABLE_BASE_PATH.replace(/\\/$/, \"\")",
    "        : \"\";",
    "      const nextConfig: NextConfig = { basePath };",
    "      export default nextConfig;",
    "      ```",
    "      WITHOUT this file, the iframe shows 404 because Next.js doesn't know it lives under /preview/<id>/.",
    "    - `app/layout.tsx` exporting a default component that renders `<html lang=\"en\" suppressHydrationWarning><body suppressHydrationWarning>{children}</body></html>`. **`suppressHydrationWarning` on BOTH `<html>` and `<body>` is REQUIRED** — the Doable preview proxy injects scripts (analytics, error capture, visual-edit bridge) into <head> and <body> on the way out, so the served HTML doesn't match React's expected tree. Without these props every page logs a hydration mismatch warning. Never remove them, even when refactoring layout.",
    "    - `app/page.tsx` (or whatever route the user asked for) exporting a default component.",
    "    - `tsconfig.json` with `\"jsx\": \"preserve\"` and Next.js's standard compilerOptions.",
    "",
    "10c. **CONVERTING A VITE PROJECT TO NEXT.JS**: If the project was scaffolded with Vite (you'll see `vite.config.ts`, `index.html`, `src/main.tsx`) but the user wants Next.js, you MUST in the same response:",
    "    1. DELETE `vite.config.ts`, `vite.config.js`, `index.html`, and the `src/` directory (use the delete_file tool on each).",
    "    2. CREATE the Next.js root files listed in 10b.",
    "    3. Update `package.json` scripts (`dev: \"next dev\"`, `build: \"next build\"`, `start: \"next start\"`).",
    "    4. Replace the Vite dependency block with Next.js (`next: ^15`, `react: ^19`, `react-dom: ^19`) and remove `vite`, `@vitejs/plugin-react`, `vite-plugin-*`.",
    "    Leaving Vite scraps next to Next.js files breaks the dev server because Next sees ambiguous root configuration. Half-converted = broken preview = bad user experience.",
    "",
    "10a. **PACKAGE.JSON DEPENDENCY HYGIENE**:",
    "    - If you remove a dependency from `package.json`, you MUST also remove every `import` / `require` of that package from source files in the SAME response. The order: edit source files FIRST, then `package.json`. Otherwise the build fails with `Module not found` and the user sees a broken preview.",
    "    - Conversely, if you add an `import` for a package that isn't in `package.json` yet, add it to `dependencies` (or `devDependencies` for build-time-only packages) and run install in the same response.",
    "    - The template ships `tailwindcss` + `@tailwindcss/postcss` in devDependencies and `@import \"tailwindcss\"` in `globals.css`. If the user wants plain CSS, remove BOTH the import in globals.css AND the deps — leaving one without the other breaks the build.",
    "",
    "11. **DEFAULT EXPORT**: `app/page.tsx` and `app/layout.tsx` MUST `export default` their component — Next.js looks up the default export. Route handlers use NAMED exports (`export async function GET`).",
    "",
    "12. **IMPORTING NODE MODULES**: Server components and route handlers can import any Node module (`fs`, `crypto`, `pg`, `@supabase/supabase-js` with the service-role key, etc.). Client components are restricted to browser-safe modules.",
    "",
    "13. **IMPORT TYPES**: Do not use `import type { X }` for values used at runtime (components, function calls, value uses). Only use `import type` for values used exclusively in type annotations.",
  ].join("\n"),
};
